version: '3.5'

services:
  postgres:
    image: postgres:14
    container_name: nestjs-postgres
    restart: always
    env_file: 
      - .env
    environment:
      PGDATA: /var/lib/postresql/data
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data  
    networks:
      - nest-app  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    ports:
      - 127.0.0.1:3000:3000
    command: npm run start:dev  
    depends_on:
      - postgres
    volumes: 
      - .:/app
      - /app/node_modules
    networks:
      - nest-app  

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nestjs-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 127.0.0.1:5050:80
    depends_on:
      - postgres
    volumes: 
      - pgadmin:/var/www/nestjs/docker-volumes/pgadmin
    networks:
      - nest-app  

networks:
  nest-app:
    driver: bridge

volumes:
  pgdata:
  pgadmin: